//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class My_Profile
    {
        public string Name { get; set; }
        public int Age { get; set; }
        public string Username { get; set; }
        public string Designation { get; set; }
        public string Location { get; set; }
        public string Img { get; set; }
        public string Password { get; set; }
        public int id { get; set; }
    
        public virtual My_Profile My_Profile1 { get; set; }
        public virtual My_Profile My_Profile2 { get; set; }
    }
}
