//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SignUp
    {
        public string Name { get; set; }
        public int Age { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
    
        public virtual SignUp SignUp1 { get; set; }
        public virtual SignUp SignUp2 { get; set; }
    }
}
